#FETCH_NAME
#SET_NAME Gelatinous Girl
#FACE Shy
Uh... Well it did feel kinda nice...
#FACE Normal
But that's not an invitation to let you poke me whenever.::You'll have to ask first.
#SET_NAME (playername)
Well can I know your name so I know who to ask?
#SET_NAME Gelatinous Girl
As long as you tell me yours first.
#SET_NAME (playername)
(playername).
#SET_NAME Gelli
Gelli.::Well I'm going to go have a nap.::Bye ^_^
#INCREASE_LOVE 11
#FINISH_DAY
#END