#FETCH_NAME
#SET_NAME (playername)
You're afraid of a cat?
#SET_NAME Cupa
#FACE Angry
Yes! I'm allergic to cats, okay?::Are you happy?
#SET_NAME (playername)
Yes.::In fact, I have a sudden urge to keep the cat.
#SET_NAME Cupa
#FACE Sad
You... you did it on purpose...::You're a jerk!
#SET_NAME (playername)
Whatever. Go back to the hole you jumped out of.
#SET_NAME Cupa
#FACE Tired
Why would you say such mean things?
#INCREASE_LOVE 1
#FINISH_DAY
#END