#SET_NAME Cupa
#FACE Happy
Danke, dass du mein Leben gerettet hast, Mister.::Puh, ich dachte schon, ich würde es nicht schaffen.
#SET_NAME Cupa
#FACE Normal
Achso, ich hab vergessen mich vorzustellen.::Ich bin Cupa, schön dich zu treffen.
#SET_NAME Cupa
Und du bist?::
#FETCH_NAME
#SET_NAME (playername)
Nenn mich einfach (playername).
#SET_NAME Cupa
(playername)? Was für ein schöner Name.
#INCREASE_LOVE 3
#FINISH_DAY
#END