#FETCH_NAME
#SET_NAME Ayumi
#FACE Sad
wah! Don't say things like that!::It's scary!
My sister got attacked by one of those monsters!
#SET_NAME (playername)
Haha! I'm only joking, I don't think he'll bite.::Even if he does, I'm sure you can do without one bone...
#SET_NAME Ayumi
Wah! St-stop talking about those things!
I don't think I'll be able to sleep tonight...
#INCREASE_LOVE 1
#FINISH_DAY
#END
