#SET_NAME Yaebi
Grmpf. Ein Erwachsener wie wird nicht seine Fassung verlieren.
Also..Was bringt dich hierher?
#SET_NAME (playername)
Nichts. Ich albere nur herum.
#SET_NAME Yaebi
W-Was?::Bist du so gelangweilt, oder nur zuviel Jugend zu verschwenden?
#SET_NAME (playername)
.........(falsches heulen)
#SET_NAME Yaebi
Oh...oohhhh....tut mir leid...
Ok,ok,äh...
Kann ich..dein Freund sein?
#SET_NAME (playername)
ähm...Okay.
(Das war gelogen.)
#DECREASE_LOVE 1
#FINISH_DAY
#END