#SET_NAME (playername)
I just want to have a little chat today.
#SET_NAME Andr
Really? Well, speak up.
#SET_NAME (playername)
How long have you been wandering alone?
#SET_NAME Andr
I'm not wandering!::I thought I've dropped something, something really important.::
But I can't remember what it s.
#SET_NAME (playername)
How can you find something not knowing what it is?
#SET_NAME Andr
Well...Maybe I'll recongize it on first sight.
#ATTACK 1
#FINISH_DAY
#END